myapp/urls.py
from django.conf.urls import url
from . import views, models

urlpatterns = [
    url(r'^prev-next/$', views.PrevNextPaginatorView.as_view(), name='prev_next'),
    url(r'^prev-next-desc/$', views.PrevNextPaginatorByDescView.as_view(), name='prev_next_desc'),
    url(r'^all/$', views.AllPaginatorView.as_view(), name='all'),
    url(r'^pure/$', views.PurePaginatorView.as_view(), name='pure'),
    url(r'^bootstrap-pure/$', views.BootstrapPurePaginatorView.as_view(), name='bootstrap_pure'),
    url(r'^share/', 
        views.SharedPaginatorView.as_view(),
        name='share')
]

myproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mysite/', include('myapp.urls', namespace='my')),
]

myapp/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField('title', max_length=255)
    content = models.CharField('content', max_length=255)

myapp/views.py
from django.views.generic import ListView
from pure_pagination.mixins import PaginationMixin
from . import models

class PrevNextPaginatorView(ListView):
    model = models.Article
    template_name = 'myapp/prev_next.html'
    paginate_by = 1
    
class PrevNextPaginatorByDescView(ListView):
    model = models.Article
    template_name = 'myapp/prev_next_desc.html'
    paginate_by = 1
    ordering = '-pk'
    
class AllPaginatorView(ListView):
    model = models.Article
    template_name = 'myapp/all.html'
    paginate_by = 1
    
    
class PurePaginatorView(PaginationMixin, ListView):
    model = models.Article
    template_name = 'myapp/pure.html'
    paginate_by = 1
    
    
class BootstrapPurePaginatorView(PaginationMixin, ListView):
    model = models.Article
    template_name = 'myapp/bootstrap_pure.html'
    paginate_by = 1
    
    
class SharedPaginatorView(PaginationMixin, ListView):
    model = models.Article
    template_name = 'myapp/share_base.html'
    paginate_by = 1

myapp/templates/myapp/all.html
<!DOCTYPE html>
<html lang="ja" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>My Site</title>
    {% load staticfiles %}
    <link href={% static 'myapp/css/pagination.css' %} rel='stylesheet'>
</head>
<body>

    <div id="main">
        <h1>All Paginator Page</h1>
        <table>
            <tr>
                <th>title</th>
                <th>content</th>
            </tr>
            {% for article in object_list %}
                <tr>
                    <td>{{ article.title }}</td>
                    <td>{{ article.content }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    
    {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li><a href="{% url 'my:all' %}?page={{ page_obj.previous_page_number }}">previous</a></li>
            {% endif %}
            {% for link_page in page_obj.paginator.page_range %}
                {% if link_page == page_obj.number %}
                    <li class="active">{{ link_page }}</li>
                {% else %}
                    <li><a href="{% url 'my:all' %}?page={{ link_page }}">{{ link_page }}</a></li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li><a href="{% url 'my:all' %}?page={{ page_obj.next_page_number }}">next</a></li>
            {% endif %}
        </ul>
    {% endif %}
</body>
</html>

myapp/templates/myapp/bootstrap_pure.html
<!DOCTYPE html>
<html lang="ja" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>My Site</title>
    {% load staticfiles %}
    <link href={% static 'myapp/css/pagination.css' %} rel='stylesheet'>
    
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-7s5uDGW3AHqw6xtJmNNtr+OBRJUlgkNJEo78P4b0yRw= sha512-nNo+yCHEyn0smMxSswnf/OnX6/KwJuZTlNZBjauKhTK0c+zT+q5JOCx0UFhXQ6rJR9jg6Es8gPuD2uZcYDLqSw==" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha256-KXn5puMvxCw+dAYznun+drMdG1IFl3agK0p/pqT9KAo= sha512-2e8qq0ETcfWRI4HJBzQiA3UoyFk6tbNyG+qSaIBZLyW9Xf3sWZHN/lxe9fTh1U45DpPf07yj94KsUHHWe4Yk1A==" crossorigin="anonymous"></script>
</head>
<body>

    <div id="main">
        <h1>django-pure-pagination & Bootstrap Page</h1>
        <table>
            <tr>
                <th>title</th>
                <th>content</th>
            </tr>
            {% for article in object_list %}
                <tr>
                    <td>{{ article.title }}</td>
                    <td>{{ article.content }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    
    {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li><a href="{% url 'my:bootstrap_pure' %}?{{ page_obj.previous_page_number.querystring }}">previous</a></li>
            {% endif %}
            {% for link_page in page_obj.pages %}
                {% if link_page %}
                    {% if link_page == page_obj.number %}
                        <li class="active"><a href="">{{ link_page }}</a></li>
                    {% else %}
                        <li><a href="{% url 'my:bootstrap_pure' %}?{{ link_page.querystring  }}">{{ link_page }}</a></li>
                    {% endif %}
                {% else %}
                    {# 省略された部分の表示内容 #}
                    <li class="disabled"><a href="#">(省略)</a></li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li><a href="{% url 'my:bootstrap_pure' %}?{{ page_obj.next_page_number.querystring }}">next</a></li>
            {% endif %}
        </ul>
    {% endif %}
</body>
</html>

myapp/templates/myapp/prev_next.html
<!DOCTYPE html>
<html lang="ja" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>My Site</title>
</head>
<body>

    <div id="main">
        <h1>Prev-Next Paginator Page</h1>
        <table>
            <tr>
                <th>title</th>
                <th>content</th>
            </tr>
            {% for article in object_list %}
                <tr>
                    <td>{{ article.title }}</td>
                    <td>{{ article.content }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>

    {% if is_paginated %}
        <div class="pagination">
            <span class="step-link">
                {% if page_obj.has_previous %}
                    <a href="{% url 'my:prev_next' %}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{% url 'my:prev_next' %}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
</body>
</html>

myapp/templates/myapp/prev_next_desc.html
<!DOCTYPE html>
<html lang="ja" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>My Site</title>
</head>
<body>

    <div id="main">
        <h1>Prev-Next Paginator Page</h1>
        <table>
            <tr>
                <th>title</th>
                <th>content</th>
            </tr>
            {% for article in object_list %}
                <tr>
                    <td>{{ article.title }}</td>
                    <td>{{ article.content }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    
    {% if is_paginated %}
        <div class="pagination">
            <span class="step-link">
                {% if page_obj.has_previous %}
                    <a href="{% url 'my:prev_next_desc' %}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{% url 'my:prev_next_desc' %}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
</body>
</html>

myapp/templates/myapp/pure.html
<!DOCTYPE html>
<html lang="ja" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>My Site</title>
    {% load staticfiles %}
    <link href={% static 'myapp/css/pagination.css' %} rel='stylesheet'>
</head>
<body>

    <div id="main">
        <h1>django-pure-pagination Page</h1>
        <table>
            <tr>
                <th>title</th>
                <th>content</th>
            </tr>
            {% for article in object_list %}
                <tr>
                    <td>{{ article.title }}</td>
                    <td>{{ article.content }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    
    {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li><a href="{% url 'my:pure' %}?{{ page_obj.previous_page_number.querystring }}">previous</a></li>
            {% endif %}
            {% for link_page in page_obj.pages %}
                {% if link_page %}
                    {% if link_page == page_obj.number %}
                        <li class="active">{{ link_page }}</li>
                    {% else %}
                        <li><a href="{% url 'my:pure' %}?{{ link_page.querystring  }}">{{ link_page }}</a></li>
                    {% endif %}
                {% else %}
                    {# 省略された部分の表示内容 #}
                    <li>(省略)</li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li><a href="{% url 'my:pure' %}?{{ page_obj.next_page_number.querystring }}">next</a></li>
            {% endif %}
        </ul>
    {% endif %}
</body>
</html>

myapp/templates/myapp/share_base.html
<!DOCTYPE html>
<html lang="ja" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>My Site</title>
    {% load staticfiles %}
    <link href={% static 'myapp/css/pagination.css' %} rel='stylesheet'>
    
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-7s5uDGW3AHqw6xtJmNNtr+OBRJUlgkNJEo78P4b0yRw= sha512-nNo+yCHEyn0smMxSswnf/OnX6/KwJuZTlNZBjauKhTK0c+zT+q5JOCx0UFhXQ6rJR9jg6Es8gPuD2uZcYDLqSw==" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha256-KXn5puMvxCw+dAYznun+drMdG1IFl3agK0p/pqT9KAo= sha512-2e8qq0ETcfWRI4HJBzQiA3UoyFk6tbNyG+qSaIBZLyW9Xf3sWZHN/lxe9fTh1U45DpPf07yj94KsUHHWe4Yk1A==" crossorigin="anonymous"></script>
</head>
<body>
    <div id="main">
        <h1>Shared pagination Page</h1>
        
        {% include "myapp/share_include.html" with url_param="my:share" %}    
        
        <table>
            <tr>
                <th>title</th>
                <th>content</th>
            </tr>
            {% for article in object_list %}
                <tr>
                    <td>{{ article.title }}</td>
                    <td>{{ article.content }}</td>
                </tr>
            {% endfor %}
        </table>
        
        {% include "myapp/share_include.html" with url_param="my:share" %}
    </div>
</body>
</html>

myapp/templates/myapp/share_include.html
{% if is_paginated %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li><a href="{% url url_param %}?{{ page_obj.previous_page_number.querystring }}">previous</a></li>
        {% endif %}
        {% for link_page in page_obj.pages %}
            {% if link_page %}
                {% if link_page == page_obj.number %}
                    <li class="active"><a href="">{{ link_page }}</a></li>
                {% else %}
                    <li><a href="{% url url_param %}?{{ link_page.querystring  }}">{{ link_page }}</a></li>
                {% endif %}
            {% else %}
                {# 省略された部分の表示内容 #}
                <li class="disabled"><a href="#">(省略)</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li><a href="{% url url_param %}?{{ page_obj.next_page_number.querystring }}">next</a></li>
        {% endif %}
    </ul>
{% endif %}